from typing import Dict, Any, List
from backend.ai.gemini.client import gemini_client

class EmergencyAgent:
    """
    Generates high-contrast, structured emergency summaries for paramedics, EMTs,
    and emergency room physicians based on verified clinical files.
    """
    async def generate_summary(
        self,
        member: Dict[str, Any],
        recent_reports: List[Dict[str, Any]],
        timeline_events: List[Dict[str, Any]]
    ) -> Dict[str, Any]:
        name = member.get("name", "Unknown Patient")
        relation = member.get("relation", "Family Member")
        age = member.get("age", 0)
        gender = member.get("gender", "Unknown")
        blood_group = member.get("bloodGroup") or member.get("blood_group", "O+")
        allergies = member.get("allergies", [])
        chronic = member.get("chronicDiseases") or member.get("chronic_diseases", [])
        medications = member.get("currentMedications") or member.get("current_medications", [])
        emergency_contact = member.get("emergencyContact") or member.get("emergency_contact", {})

        # Build clean clinical summary object
        formatted_card = {
            "patientName": name,
            "relation": relation,
            "age": age,
            "gender": gender,
            "bloodGroup": blood_group,
            "allergies": allergies if allergies else ["None Reported"],
            "chronicConditions": chronic if chronic else ["None Documented"],
            "activeMedications": medications if medications else ["None"],
            "emergencyContact": {
                "name": emergency_contact.get("name", "Not Listed"),
                "relation": emergency_contact.get("relation", "Contact"),
                "phone": emergency_contact.get("phone", "N/A")
            },
            "recentReportsCount": len(recent_reports),
            "surgeries": [e.get("title") for e in timeline_events if "surgery" in e.get("type", "").lower() or "procedure" in e.get("type", "").lower()],
            "vitalAlert": "⚠️ HIGH-RISK ALLERGY ALERT: Cross-verify all IV antibiotics before administration." if allergies else "Stable baseline profile."
        }

        # Text snippet for quick sharing (WhatsApp, SMS, EMT clipboards)
        shareable_text = (
            f"🚨 *EMERGENCY MEDICAL SUMMARY* 🚨\n"
            f"*Patient*: {name} ({relation})\n"
            f"*Blood Group*: 🩸 {blood_group}\n"
            f"*Age / Gender*: {age} yrs / {gender}\n"
            f"*Critical Allergies*: {', '.join(formatted_card['allergies'])}\n"
            f"*Chronic Conditions*: {', '.join(formatted_card['chronicConditions'])}\n"
            f"*Active Medications*: {'; '.join(formatted_card['activeMedications'])}\n"
            f"*Emergency Contact*: {formatted_card['emergencyContact']['name']} ({formatted_card['emergencyContact']['relation']}) - {formatted_card['emergencyContact']['phone']}\n"
            f"_Generated by Family Health Concierge AI_"
        )

        formatted_card["shareableText"] = shareable_text
        return formatted_card

emergency_agent = EmergencyAgent()
